apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: nginx-test
  policyTypes:
  - Egress
  egress:
  # Regra para DNS (UDP e TCP porta 53) para qualquer lugar
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53